baseURL = "/"
languageCode = "en-us"
title = "kubuntuclaps blog"
rssLimit = 20
minify = false

[Author]
  name = "kubuntuclaps"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]